[font]
builtin_box_drawing = true
size = 17

[font.normal]
family = "Iosevka Nerd Font"
[font.glyph_offset]
x = 0
y = 1

[window]
dynamic_padding = true
dynamic_title = false
opacity = 0.99
blur = true
resize_increments = true

[window.padding]
x = 0
y = 0

[mouse]
hide_when_typing = true

[cursor]
style.shape = "Block"
style.blinking="Off"

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/themes/themes/solarized_dark.toml"
]

[terminal]
shell = "/usr/bin/bash"

